CREATE TABLE spending_limits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    limit_amount DECIMAL(19,2) NOT NULL,
    period VARCHAR(10) NOT NULL,
    CONSTRAINT fk_spending_limits_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_spending_limits_category FOREIGN KEY (category_id) REFERENCES categories(id)
);
